### ISSUE TITLE
reflect: call of reflect.Value.IsNil on struct Value

### ISSUE THREAD

**Issue by MihaiSandor** [kardianos/hl7#1]
## When I tried to Decode this message with v2.50 I just got an error only for DRG.

```go
2022/12/14 21:40:41 http: panic serving 127.0.0.1:: reflect: call of reflect.Value.IsNil on struct Value
goroutine 62 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1850 +0xbf
panic({0x1329900, 0xc000496c18})
        /usr/local/go/src/runtime/panic.go:890 +0x262
reflect.Value.IsNil(...)
        /usr/local/go/src/reflect/value.go:1554
github.com/kardianos/hl7.(*walker).fullInArray(0x16b4f30?, 0x13d00c0?)
        /Users/lms/Desktop/projects/github.com/kardianos/hl7/decodeGroup.go:297 +0x125
github.com/kardianos/hl7.(*walker).digest(0xc000392d00, 0xc000392d00?, {0x12d2de0, 0xc0005377c0?})
        /Users/lms/Desktop/projects/github.com/kardianos/hl7/decodeGroup.go:167 +0x207
github.com/kardianos/hl7.(*walker).process(0xc000392d00, {0xc000392cc0, 0x3, 0x4})
        /Users/lms/Desktop/projects/github.com/kardianos/hl7/decodeGroup.go:59 +0x138
github.com/kardianos/hl7.group({0xc000392cc0, 0x3, 0x4}, {0x16b2470?, 0x19074a0?})
        /Users/lms/Desktop/projects/github.com/kardianos/hl7/decodeGroup.go:83 +0x5f
github.com/kardianos/hl7.(*Decoder).DecodeGroup(...)
        /Users/lms/Desktop/projects/github.com/kardianos/hl7/decode.go:63
github.com/kardianos/hl7.(*Decoder).Decode(0xc000012528, {0xc000548600?, 0x71?, 0xc000016070?})
        /Users/lms/Desktop/projects/github.com/kardianos/hl7/decode.go:54 +0x8b
main.(*Decoder).parse(0xc000014028, 0xc00053e9f8)
        /Users/lms/Desktop/projects/github.com/test/main.go:18 +0x56
main.(*Decoder).raw(0x3d5dc0?, {0x16b1b60?, 0xc0003de1c0}, 0x10c16c9?)
        /Users/lms/Desktop/projects/github.com/test/main.go:32 +0x117
net/http.HandlerFunc.ServeHTTP(0xc0003de1c0?, {0x16b1b60?, 0xc0003de1c0?}, 0x1067040?)
        /usr/local/go/src/net/http/server.go:2109 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x16b1b60, 0xc0003de1c0}, 0xc000138d00)
        /usr/local/go/src/net/http/server.go:2487 +0x149
net/http.serverHandler.ServeHTTP({0x16b0f70?}, {0x16b1b60, 0xc0003de1c0}, 0xc000138d00)
        /usr/local/go/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc000537040, {0x16b1fc0, 0xc000266f00})
        /usr/local/go/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3102 +0x4db
```

The error looks like to be [here](https://github.com/kardianos/hl7/blob/master/decodeGroup.go#L297): 

```text
MSH|^~\&|SMTH|0000^SMTH^HOS|SMTH|0000^SMTH|20190306082042||ADT^A03|random|P|1
DRG|123^Feaver
DRG|456^Feaver
```

## For DG1 works well:

```text
MSH|^~\&|SMTH|0000^SMTH^HOS|SMTH|0000^SMTH|20190306082042||ADT^A03|random|P|1
DG1|1|ICD10|R04^Other problems
DG1|2|ICD10|D68^Other defects
DG1|3|ICD10|A12^Pain
```

You can test this bug here in playground (https://go.dev/play/p/_sZIkrk-EGD)

Did you have any idea?

**Comment by kardianos** [comment]
Trigger ADT_A03 only has a single *DRG field. Your message attempts to set that field multiple times which is an error. Due to a bug in the code, there is a panic rather then an error.  I've corrected this panic and improved the error, and added a test case for this message error. I've tagged a new release v1.0.7.

Do you know why you are consuming a message with an ADT_A03 trigger sending multiple DRG segments? I looked at the spec and it doesn't appear to be a repeating field. Of course, if you need to consume malformed messages, you can copy the h250 package locally and modify the trigger locally so the DRG is a `[]DRG` type rather then a `*DRG` type.

**Comment by kardianos** [comment]
playground link with new tagged version: https://go.dev/play/p/skZP799Bz9f

**Comment by MihaiSandor** [comment]
Hi @kardianos,

Thank you so much for fixing the panic.
The thing is right now I'm doing an integration with Bamboo and in the samples I found the example with multiple DRG, maybe in production it won't be like that.

But the thing is if I am using `DecodeList` works well (without panic)
